name: aleef
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.4
  http: ^1.6.0
  provider: ^6.1.5+1
  flutter_secure_storage: ^10.0.0
  get_it: ^7.7.0
  font_awesome_flutter: ^11.0.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.2.1
  flutter_screenutil: ^5.9.3
  device_preview: ^1.3.1
  carousel_slider: ^5.1.2
  dio: ^5.9.2
  audioplayers: ^6.6.0
  intl: ^0.20.2
  socket_io_client: ^3.1.1
  shimmer: ^3.0.0
  firebase_messaging: ^14.7.10
  firebase_core: ^2.30.0
  lucide_icons_flutter: ^3.1.13
  cached_network_image: ^3.4.1
  file_picker: ^8.1.7
  google_sign_in: ^6.2.2
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/cat_3d.png
    - assets/images/cat.png
    - lib/features/profile/presentation/widgets/edit_profile/
    - assets/
    - assets/images/svgs/
    - assets/sounds/
    - assets/images/chat_bot.png
    - lib/features/store/presentation/pages/
    - lib/features/onboarding/presentation/pages/
    - lib/features/doctor/home/data/models/